/* AURA UI — Extended Components (New Categories) */
const EXTRA_COMPONENTS=[
{id:'glassmorphism-navbar',title:'Glass Navbar',category:'navbar',tags:['nav','glass','sticky'],desc:'Frosted glass navigation bar with blur effect.',featured:true,isNew:true,
preview:`<style>body{margin:0;font-family:Inter,sans-serif;background:#0b0f1a;height:100vh;}.gnav{display:flex;align-items:center;justify-content:space-between;padding:14px 24px;background:rgba(255,255,255,.06);backdrop-filter:blur(16px);border-bottom:1px solid rgba(255,255,255,.08);}.gnav-logo{font-size:16px;font-weight:800;color:#fff;}.gnav-links{display:flex;gap:20px;}.gnav-links a{color:rgba(255,255,255,.6);font-size:13px;font-weight:500;text-decoration:none;transition:color .2s;}.gnav-links a:hover{color:#fff;}.gnav-btn{padding:8px 18px;background:linear-gradient(135deg,#7c3aed,#2563eb);color:#fff;border:none;border-radius:8px;font-size:12px;font-weight:700;cursor:pointer;}</style><nav class="gnav"><span class="gnav-logo">Brand</span><div class="gnav-links"><a href="#">Home</a><a href="#">Products</a><a href="#">Pricing</a><a href="#">Contact</a></div><button class="gnav-btn">Get Started</button></nav>`,
code:`<nav class="gnav"><span class="gnav-logo">Brand</span><div class="gnav-links"><a href="#">Home</a><a href="#">Products</a><a href="#">Pricing</a><a href="#">Contact</a></div><button class="gnav-btn">Get Started</button></nav>\n\n<style>\n.gnav{display:flex;align-items:center;justify-content:space-between;padding:14px 24px;background:rgba(255,255,255,.06);backdrop-filter:blur(16px);border-bottom:1px solid rgba(255,255,255,.08);}\n.gnav-logo{font-size:16px;font-weight:800;color:#fff;}\n.gnav-links{display:flex;gap:20px;}\n.gnav-links a{color:rgba(255,255,255,.6);font-size:13px;font-weight:500;text-decoration:none;}\n.gnav-links a:hover{color:#fff;}\n.gnav-btn{padding:8px 18px;background:linear-gradient(135deg,#7c3aed,#2563eb);color:#fff;border:none;border-radius:8px;font-size:12px;font-weight:700;}\n</style>`},

{id:'gradient-hero',title:'Gradient Hero',category:'hero',tags:['hero','gradient','cta'],desc:'Bold hero section with gradient text and CTA buttons.',featured:true,isNew:true,
preview:`<style>body{margin:0;font-family:Inter,sans-serif;background:#050810;display:flex;align-items:center;justify-content:center;height:100vh;text-align:center;}.gh{max-width:400px;padding:20px;}.gh h1{font-size:28px;font-weight:900;color:#fff;line-height:1.1;margin-bottom:10px;}.gh h1 span{background:linear-gradient(135deg,#a78bfa,#60a5fa);-webkit-background-clip:text;-webkit-text-fill-color:transparent;}.gh p{font-size:12px;color:rgba(255,255,255,.5);margin-bottom:16px;}.gh-btns{display:flex;gap:10px;justify-content:center;}.gh-btn{padding:10px 20px;border-radius:8px;font-size:12px;font-weight:700;border:none;cursor:pointer;}.gh-p{background:linear-gradient(135deg,#7c3aed,#2563eb);color:#fff;}.gh-s{background:transparent;color:#fff;border:1px solid rgba(255,255,255,.15);}</style><div class="gh"><h1>Build <span>Amazing</span> Websites</h1><p>Production-ready components for modern web development.</p><div class="gh-btns"><button class="gh-btn gh-p">Get Started</button><button class="gh-btn gh-s">Learn More</button></div></div>`,
code:`<section class="gh"><h1>Build <span>Amazing</span> Websites</h1><p>Production-ready components for modern web development.</p><div class="gh-btns"><button class="gh-btn gh-p">Get Started</button><button class="gh-btn gh-s">Learn More</button></div></section>\n\n<style>\n.gh{text-align:center;padding:80px 24px;}\n.gh h1{font-size:56px;font-weight:900;color:#fff;line-height:1.1;}\n.gh h1 span{background:linear-gradient(135deg,#a78bfa,#60a5fa);-webkit-background-clip:text;-webkit-text-fill-color:transparent;}\n.gh p{font-size:18px;color:rgba(255,255,255,.5);margin:16px 0 32px;}\n.gh-btns{display:flex;gap:14px;justify-content:center;}\n.gh-btn{padding:14px 28px;border-radius:10px;font-size:15px;font-weight:700;border:none;cursor:pointer;}\n.gh-p{background:linear-gradient(135deg,#7c3aed,#2563eb);color:#fff;}\n.gh-s{background:transparent;color:#fff;border:1px solid rgba(255,255,255,.15);}\n</style>`},

{id:'pricing-table',title:'Pricing Table',category:'pricing',tags:['pricing','plans','business'],desc:'Three-tier pricing table with popular highlight.',featured:true,isNew:true,
preview:`<style>body{margin:0;font-family:Inter,sans-serif;background:#0b0f1a;display:flex;align-items:center;justify-content:center;height:100vh;gap:10px;padding:10px;}.pt{width:140px;padding:18px 14px;background:#0f1629;border:1px solid rgba(255,255,255,.08);border-radius:14px;text-align:center;}.pt.pop{border-color:#7c3aed;box-shadow:0 0 30px rgba(124,58,237,.2);}.pt-name{font-size:11px;font-weight:700;color:rgba(255,255,255,.5);text-transform:uppercase;letter-spacing:.08em;}.pt-price{font-size:26px;font-weight:900;color:#fff;margin:6px 0;}.pt-price span{font-size:11px;color:rgba(255,255,255,.3);font-weight:500;}.pt-feat{font-size:10px;color:rgba(255,255,255,.4);line-height:1.8;margin:10px 0;text-align:left;}.pt-btn{width:100%;padding:8px;border:none;border-radius:8px;font-size:11px;font-weight:700;cursor:pointer;}.pt-btn-o{background:transparent;color:#a78bfa;border:1px solid rgba(124,58,237,.3);}.pt-btn-p{background:linear-gradient(135deg,#7c3aed,#2563eb);color:#fff;}.pop-label{font-size:9px;font-weight:700;background:linear-gradient(135deg,#7c3aed,#2563eb);color:#fff;padding:2px 8px;border-radius:20px;margin-bottom:8px;display:inline-block;}</style><div class="pt"><div class="pt-name">Starter</div><div class="pt-price">$9<span>/mo</span></div><div class="pt-feat">✓ 5 Projects<br>✓ Basic Support<br>✓ 1 GB Storage</div><button class="pt-btn pt-btn-o">Choose</button></div><div class="pt pop"><span class="pop-label">Popular</span><div class="pt-name">Pro</div><div class="pt-price">$29<span>/mo</span></div><div class="pt-feat">✓ Unlimited Projects<br>✓ Priority Support<br>✓ 100 GB Storage</div><button class="pt-btn pt-btn-p">Choose</button></div><div class="pt"><div class="pt-name">Enterprise</div><div class="pt-price">$99<span>/mo</span></div><div class="pt-feat">✓ Everything in Pro<br>✓ Dedicated Manager<br>✓ Custom SLA</div><button class="pt-btn pt-btn-o">Contact</button></div>`,
code:`<!-- See preview for full pricing table HTML -->\n<div class="pricing-grid">\n  <div class="pt">...</div>\n  <div class="pt pop">...</div>\n  <div class="pt">...</div>\n</div>\n\n<style>\n.pricing-grid{display:flex;gap:20px;justify-content:center;padding:40px;}\n.pt{width:300px;padding:32px;background:#0f1629;border:1px solid rgba(255,255,255,.08);border-radius:20px;text-align:center;}\n.pt.pop{border-color:#7c3aed;box-shadow:0 0 40px rgba(124,58,237,.2);}\n.pt-name{font-size:13px;font-weight:700;color:rgba(255,255,255,.5);text-transform:uppercase;}\n.pt-price{font-size:42px;font-weight:900;color:#fff;margin:8px 0;}\n.pt-btn-p{background:linear-gradient(135deg,#7c3aed,#2563eb);color:#fff;border:none;padding:12px;border-radius:10px;width:100%;font-weight:700;}\n</style>`},

{id:'testimonial-card-v2',title:'Testimonial Card',category:'testimonial',tags:['review','quote','social'],desc:'Customer testimonial with avatar and stars.',featured:true,isNew:true,
preview:`<style>body{margin:0;font-family:Inter,sans-serif;background:#0b0f1a;display:flex;align-items:center;justify-content:center;height:100vh;}.tc{width:240px;padding:22px;background:#0f1629;border:1px solid rgba(255,255,255,.08);border-radius:16px;}.tc-stars{color:#fbbf24;font-size:12px;margin-bottom:10px;}.tc-quote{font-size:12px;color:rgba(255,255,255,.6);line-height:1.6;margin-bottom:14px;font-style:italic;}.tc-author{display:flex;align-items:center;gap:10px;}.tc-av{width:32px;height:32px;border-radius:50%;background:linear-gradient(135deg,#7c3aed,#2563eb);display:flex;align-items:center;justify-content:center;color:#fff;font-size:12px;font-weight:800;}.tc-name{font-size:12px;font-weight:700;color:#fff;}.tc-role{font-size:10px;color:rgba(255,255,255,.4);}</style><div class="tc"><div class="tc-stars">★★★★★</div><p class="tc-quote">"This UI library saved us weeks of development time. The components are beautiful and production-ready."</p><div class="tc-author"><div class="tc-av">SK</div><div><div class="tc-name">Sarah Kim</div><div class="tc-role">CTO, TechCorp</div></div></div></div>`,
code:`<div class="tc"><div class="tc-stars">★★★★★</div><p class="tc-quote">"Amazing UI library!"</p><div class="tc-author"><div class="tc-av">SK</div><div><div class="tc-name">Sarah Kim</div><div class="tc-role">CTO</div></div></div></div>\n\n<style>\n.tc{padding:24px;background:#0f1629;border:1px solid rgba(255,255,255,.08);border-radius:16px;}\n.tc-stars{color:#fbbf24;font-size:14px;margin-bottom:12px;}\n.tc-quote{font-size:14px;color:rgba(255,255,255,.6);line-height:1.7;font-style:italic;margin-bottom:16px;}\n.tc-author{display:flex;align-items:center;gap:12px;}\n.tc-av{width:40px;height:40px;border-radius:50%;background:linear-gradient(135deg,#7c3aed,#2563eb);display:flex;align-items:center;justify-content:center;color:#fff;font-weight:800;}\n.tc-name{font-size:13px;font-weight:700;color:#fff;}\n.tc-role{font-size:11px;color:rgba(255,255,255,.4);}\n</style>`},

{id:'minimal-footer',title:'Minimal Footer',category:'footer',tags:['footer','links','brand'],desc:'Clean four-column footer with brand and links.',featured:false,isNew:true,
preview:`<style>body{margin:0;font-family:Inter,sans-serif;background:#0b0f1a;display:flex;align-items:flex-end;height:100vh;}.mf{width:100%;padding:24px 20px 16px;border-top:1px solid rgba(255,255,255,.06);}.mf-grid{display:grid;grid-template-columns:2fr 1fr 1fr 1fr;gap:16px;margin-bottom:16px;}.mf-brand{font-size:14px;font-weight:800;color:#fff;margin-bottom:6px;}.mf-desc{font-size:10px;color:rgba(255,255,255,.4);line-height:1.5;}.mf h4{font-size:10px;font-weight:700;color:rgba(255,255,255,.3);text-transform:uppercase;letter-spacing:.08em;margin-bottom:6px;}.mf a{display:block;font-size:11px;color:rgba(255,255,255,.5);padding:2px 0;text-decoration:none;}.mf-bottom{font-size:9px;color:rgba(255,255,255,.2);border-top:1px solid rgba(255,255,255,.06);padding-top:10px;}</style><footer class="mf"><div class="mf-grid"><div><div class="mf-brand">AURA UI</div><p class="mf-desc">Beautiful components for modern websites.</p></div><div><h4>Product</h4><a>Components</a><a>Templates</a><a>Pricing</a></div><div><h4>Resources</h4><a>Docs</a><a>Blog</a><a>Support</a></div><div><h4>Company</h4><a>About</a><a>Careers</a><a>Contact</a></div></div><div class="mf-bottom">© 2026 AURA UI. MIT License.</div></footer>`,
code:`<footer class="mf">...</footer>\n\n<style>\n.mf{padding:48px 24px;border-top:1px solid rgba(255,255,255,.06);}\n.mf-grid{display:grid;grid-template-columns:2fr 1fr 1fr 1fr;gap:32px;margin-bottom:32px;}\n.mf-brand{font-size:18px;font-weight:800;color:#fff;}\n.mf h4{font-size:11px;font-weight:700;color:rgba(255,255,255,.3);text-transform:uppercase;letter-spacing:.1em;margin-bottom:12px;}\n.mf a{display:block;font-size:13px;color:rgba(255,255,255,.5);padding:4px 0;text-decoration:none;}\n.mf a:hover{color:#fff;}\n</style>`},

{id:'login-form',title:'Login Form',category:'auth',tags:['login','auth','form'],desc:'Dark themed login form with email and password.',featured:true,isNew:true,
preview:`<style>body{margin:0;font-family:Inter,sans-serif;background:#0b0f1a;display:flex;align-items:center;justify-content:center;height:100vh;}.lf{width:240px;padding:24px;background:#0f1629;border:1px solid rgba(255,255,255,.08);border-radius:16px;}.lf h2{font-size:18px;font-weight:800;color:#fff;margin-bottom:4px;}.lf-sub{font-size:11px;color:rgba(255,255,255,.4);margin-bottom:16px;}.lf-group{margin-bottom:10px;}.lf-label{display:block;font-size:11px;font-weight:600;color:rgba(255,255,255,.5);margin-bottom:4px;}.lf-input{width:100%;padding:10px 12px;background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.1);border-radius:8px;color:#fff;font-size:12px;outline:none;box-sizing:border-box;}.lf-input:focus{border-color:#7c3aed;}.lf-btn{width:100%;padding:10px;background:linear-gradient(135deg,#7c3aed,#2563eb);color:#fff;border:none;border-radius:8px;font-size:13px;font-weight:700;cursor:pointer;margin-top:6px;}.lf-link{text-align:center;margin-top:10px;font-size:11px;color:rgba(255,255,255,.4);}.lf-link a{color:#a78bfa;text-decoration:none;}</style><div class="lf"><h2>Welcome back</h2><p class="lf-sub">Sign in to your account</p><div class="lf-group"><label class="lf-label">Email</label><input class="lf-input" type="email" placeholder="you@email.com"></div><div class="lf-group"><label class="lf-label">Password</label><input class="lf-input" type="password" placeholder="••••••••"></div><button class="lf-btn">Sign In</button><p class="lf-link">Don't have an account? <a>Sign up</a></p></div>`,
code:`<div class="lf"><h2>Welcome back</h2><p class="lf-sub">Sign in to your account</p><div class="lf-group"><label class="lf-label">Email</label><input class="lf-input" type="email" placeholder="you@email.com"></div><div class="lf-group"><label class="lf-label">Password</label><input class="lf-input" type="password" placeholder="••••••••"></div><button class="lf-btn">Sign In</button></div>\n\n<style>\n.lf{max-width:400px;padding:32px;background:#0f1629;border:1px solid rgba(255,255,255,.08);border-radius:20px;}\n.lf h2{font-size:24px;font-weight:800;color:#fff;}\n.lf-input{width:100%;padding:12px 16px;background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.1);border-radius:10px;color:#fff;font-size:14px;outline:none;box-sizing:border-box;}\n.lf-input:focus{border-color:#7c3aed;box-shadow:0 0 0 3px rgba(124,58,237,.15);}\n.lf-btn{width:100%;padding:12px;background:linear-gradient(135deg,#7c3aed,#2563eb);color:#fff;border:none;border-radius:10px;font-size:14px;font-weight:700;}\n</style>`},

{id:'contact-form',title:'Contact Form',category:'form',tags:['contact','form','business'],desc:'Contact form with name, email, and message fields.',featured:false,isNew:true,
preview:`<style>body{margin:0;font-family:Inter,sans-serif;background:#0b0f1a;display:flex;align-items:center;justify-content:center;height:100vh;}.cf{width:260px;padding:22px;background:#0f1629;border:1px solid rgba(255,255,255,.08);border-radius:16px;}.cf h3{font-size:16px;font-weight:800;color:#fff;margin-bottom:12px;}.cf-row{display:flex;gap:8px;margin-bottom:8px;}.cf-input{width:100%;padding:9px 12px;background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.1);border-radius:8px;color:#fff;font-size:11px;outline:none;box-sizing:border-box;margin-bottom:8px;}.cf-input:focus{border-color:#7c3aed;}.cf-ta{resize:none;height:60px;font-family:inherit;}.cf-btn{width:100%;padding:10px;background:linear-gradient(135deg,#7c3aed,#2563eb);color:#fff;border:none;border-radius:8px;font-size:12px;font-weight:700;cursor:pointer;}</style><div class="cf"><h3>Get in Touch</h3><div class="cf-row"><input class="cf-input" placeholder="First name"><input class="cf-input" placeholder="Last name"></div><input class="cf-input" placeholder="Email address"><textarea class="cf-input cf-ta" placeholder="Your message..."></textarea><button class="cf-btn">Send Message</button></div>`,
code:`<div class="cf"><h3>Get in Touch</h3><div class="cf-row"><input class="cf-input" placeholder="First name"><input class="cf-input" placeholder="Last name"></div><input class="cf-input" placeholder="Email"><textarea class="cf-input cf-ta" placeholder="Message..."></textarea><button class="cf-btn">Send Message</button></div>\n\n<style>\n.cf{max-width:500px;padding:32px;background:#0f1629;border:1px solid rgba(255,255,255,.08);border-radius:20px;}\n.cf-row{display:flex;gap:12px;}\n.cf-input{width:100%;padding:12px 16px;background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.1);border-radius:10px;color:#fff;font-size:14px;outline:none;box-sizing:border-box;margin-bottom:12px;}\n.cf-input:focus{border-color:#7c3aed;}\n.cf-btn{width:100%;padding:14px;background:linear-gradient(135deg,#7c3aed,#2563eb);color:#fff;border:none;border-radius:10px;font-weight:700;}\n</style>`},

{id:'data-table',title:'Data Table',category:'table',tags:['table','data','rows'],desc:'Striped data table with status badges.',featured:false,isNew:true,
preview:`<style>body{margin:0;font-family:Inter,sans-serif;background:#0b0f1a;display:flex;align-items:center;justify-content:center;height:100vh;padding:10px;}.dt{width:340px;background:#0f1629;border:1px solid rgba(255,255,255,.08);border-radius:12px;overflow:hidden;}.dt table{width:100%;border-collapse:collapse;}.dt th{text-align:left;padding:10px 14px;font-size:10px;font-weight:700;color:rgba(255,255,255,.4);text-transform:uppercase;letter-spacing:.06em;border-bottom:1px solid rgba(255,255,255,.06);}.dt td{padding:10px 14px;font-size:11px;color:rgba(255,255,255,.7);border-bottom:1px solid rgba(255,255,255,.04);}.dt tr:hover td{background:rgba(124,58,237,.04);}.dt-badge{padding:2px 8px;border-radius:20px;font-size:9px;font-weight:700;}.dt-active{background:rgba(16,185,129,.15);color:#34d399;}.dt-pending{background:rgba(245,158,11,.15);color:#fbbf24;}</style><div class="dt"><table><thead><tr><th>Name</th><th>Role</th><th>Status</th></tr></thead><tbody><tr><td>Alex Chen</td><td>Developer</td><td><span class="dt-badge dt-active">Active</span></td></tr><tr><td>Maria Lopez</td><td>Designer</td><td><span class="dt-badge dt-active">Active</span></td></tr><tr><td>John Park</td><td>Manager</td><td><span class="dt-badge dt-pending">Pending</span></td></tr></tbody></table></div>`,
code:`<div class="dt"><table><thead><tr><th>Name</th><th>Role</th><th>Status</th></tr></thead><tbody><tr><td>Alex</td><td>Dev</td><td><span class="dt-badge dt-active">Active</span></td></tr></tbody></table></div>\n\n<style>\n.dt{background:#0f1629;border:1px solid rgba(255,255,255,.08);border-radius:16px;overflow:hidden;}\n.dt table{width:100%;border-collapse:collapse;}\n.dt th{text-align:left;padding:14px 18px;font-size:11px;font-weight:700;color:rgba(255,255,255,.4);text-transform:uppercase;border-bottom:1px solid rgba(255,255,255,.06);}\n.dt td{padding:14px 18px;font-size:13px;color:rgba(255,255,255,.7);border-bottom:1px solid rgba(255,255,255,.04);}\n.dt-badge{padding:3px 10px;border-radius:20px;font-size:10px;font-weight:700;}\n.dt-active{background:rgba(16,185,129,.15);color:#34d399;}\n</style>`},

{id:'confirm-modal',title:'Confirm Modal',category:'modal',tags:['modal','dialog','confirm'],desc:'Confirmation dialog with action buttons.',featured:false,isNew:true,
preview:`<style>body{margin:0;font-family:Inter,sans-serif;background:#0b0f1a;display:flex;align-items:center;justify-content:center;height:100vh;}.cm-bg{position:fixed;inset:0;background:rgba(0,0,0,.5);display:flex;align-items:center;justify-content:center;}.cm{width:280px;padding:24px;background:#0f1629;border:1px solid rgba(255,255,255,.1);border-radius:16px;text-align:center;}.cm-icon{width:48px;height:48px;border-radius:50%;background:rgba(239,68,68,.15);display:flex;align-items:center;justify-content:center;margin:0 auto 14px;font-size:20px;}.cm h3{font-size:16px;font-weight:800;color:#fff;margin-bottom:6px;}.cm p{font-size:12px;color:rgba(255,255,255,.5);margin-bottom:18px;line-height:1.5;}.cm-btns{display:flex;gap:8px;}.cm-btn{flex:1;padding:10px;border-radius:8px;font-size:12px;font-weight:700;border:none;cursor:pointer;}.cm-cancel{background:rgba(255,255,255,.06);color:rgba(255,255,255,.6);border:1px solid rgba(255,255,255,.1);}.cm-delete{background:#ef4444;color:#fff;}</style><div class="cm-bg"><div class="cm"><div class="cm-icon">⚠</div><h3>Delete Item?</h3><p>This action cannot be undone. All data will be permanently removed.</p><div class="cm-btns"><button class="cm-btn cm-cancel">Cancel</button><button class="cm-btn cm-delete">Delete</button></div></div></div>`,
code:`<div class="cm"><div class="cm-icon">⚠</div><h3>Delete Item?</h3><p>This action cannot be undone.</p><div class="cm-btns"><button class="cm-btn cm-cancel">Cancel</button><button class="cm-btn cm-delete">Delete</button></div></div>\n\n<style>\n.cm{max-width:400px;padding:32px;background:#0f1629;border:1px solid rgba(255,255,255,.1);border-radius:20px;text-align:center;}\n.cm-icon{width:56px;height:56px;border-radius:50%;background:rgba(239,68,68,.15);display:flex;align-items:center;justify-content:center;margin:0 auto 16px;font-size:24px;}\n.cm-btns{display:flex;gap:10px;}\n.cm-btn{flex:1;padding:12px;border-radius:10px;font-size:13px;font-weight:700;border:none;cursor:pointer;}\n.cm-cancel{background:rgba(255,255,255,.06);color:rgba(255,255,255,.6);}\n.cm-delete{background:#ef4444;color:#fff;}\n</style>`},

{id:'product-card',title:'Product Card',category:'ecommerce',tags:['product','shop','price'],desc:'E-commerce product card with image placeholder and price.',featured:true,isNew:true,
preview:`<style>body{margin:0;font-family:Inter,sans-serif;background:#0b0f1a;display:flex;align-items:center;justify-content:center;height:100vh;}.pc{width:200px;background:#0f1629;border:1px solid rgba(255,255,255,.08);border-radius:16px;overflow:hidden;}.pc-img{height:140px;background:linear-gradient(135deg,#1e0533,#0b1845);display:flex;align-items:center;justify-content:center;font-size:40px;}.pc-body{padding:14px;}.pc-name{font-size:13px;font-weight:700;color:#fff;margin-bottom:4px;}.pc-desc{font-size:10px;color:rgba(255,255,255,.4);margin-bottom:10px;}.pc-bottom{display:flex;align-items:center;justify-content:space-between;}.pc-price{font-size:18px;font-weight:900;color:#fff;}.pc-price span{font-size:11px;color:rgba(255,255,255,.3);text-decoration:line-through;margin-left:6px;}.pc-cart{padding:8px 14px;background:linear-gradient(135deg,#7c3aed,#2563eb);color:#fff;border:none;border-radius:8px;font-size:10px;font-weight:700;cursor:pointer;}</style><div class="pc"><div class="pc-img">👟</div><div class="pc-body"><div class="pc-name">Premium Sneakers</div><div class="pc-desc">Lightweight running shoes</div><div class="pc-bottom"><div class="pc-price">$129<span>$179</span></div><button class="pc-cart">Add</button></div></div></div>`,
code:`<div class="pc"><div class="pc-img">👟</div><div class="pc-body"><div class="pc-name">Premium Sneakers</div><div class="pc-price">$129<span>$179</span></div><button class="pc-cart">Add to Cart</button></div></div>\n\n<style>\n.pc{width:280px;background:#0f1629;border:1px solid rgba(255,255,255,.08);border-radius:20px;overflow:hidden;}\n.pc-img{height:200px;background:linear-gradient(135deg,#1e0533,#0b1845);display:flex;align-items:center;justify-content:center;font-size:60px;}\n.pc-body{padding:20px;}\n.pc-name{font-size:16px;font-weight:700;color:#fff;}\n.pc-price{font-size:22px;font-weight:900;color:#fff;}\n.pc-price span{font-size:13px;color:rgba(255,255,255,.3);text-decoration:line-through;}\n.pc-cart{padding:10px 20px;background:linear-gradient(135deg,#7c3aed,#2563eb);color:#fff;border:none;border-radius:10px;font-weight:700;}\n</style>`},

{id:'feature-grid',title:'Feature Grid',category:'feature',tags:['features','grid','icons'],desc:'Three-column feature grid with icons.',featured:false,isNew:true,
preview:`<style>body{margin:0;font-family:Inter,sans-serif;background:#0b0f1a;display:flex;align-items:center;justify-content:center;height:100vh;padding:10px;}.fg{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;max-width:360px;}.fg-item{padding:16px 14px;background:#0f1629;border:1px solid rgba(255,255,255,.07);border-radius:12px;text-align:center;transition:all .3s;}.fg-item:hover{border-color:rgba(124,58,237,.4);transform:translateY(-3px);}.fg-ic{width:36px;height:36px;border-radius:10px;background:linear-gradient(135deg,rgba(124,58,237,.25),rgba(124,58,237,.08));display:flex;align-items:center;justify-content:center;margin:0 auto 8px;font-size:16px;}.fg-item h4{font-size:11px;font-weight:700;color:#fff;margin-bottom:3px;}.fg-item p{font-size:9px;color:rgba(255,255,255,.4);line-height:1.4;}</style><div class="fg"><div class="fg-item"><div class="fg-ic">⚡</div><h4>Fast</h4><p>Lightning speed</p></div><div class="fg-item"><div class="fg-ic">🛡</div><h4>Secure</h4><p>Enterprise grade</p></div><div class="fg-item"><div class="fg-ic">✦</div><h4>Beautiful</h4><p>Premium design</p></div><div class="fg-item"><div class="fg-ic">📱</div><h4>Responsive</h4><p>Any screen size</p></div><div class="fg-item"><div class="fg-ic">♿</div><h4>Accessible</h4><p>WCAG compliant</p></div><div class="fg-item"><div class="fg-ic">🔧</div><h4>Customizable</h4><p>Full control</p></div></div>`,
code:`<!-- 3-column feature grid -->\n<div class="fg">...</div>\n\n<style>\n.fg{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;}\n.fg-item{padding:24px;background:#0f1629;border:1px solid rgba(255,255,255,.07);border-radius:16px;text-align:center;transition:all .3s;}\n.fg-item:hover{border-color:rgba(124,58,237,.4);transform:translateY(-4px);}\n.fg-ic{width:48px;height:48px;border-radius:12px;background:linear-gradient(135deg,rgba(124,58,237,.25),rgba(124,58,237,.08));display:flex;align-items:center;justify-content:center;margin:0 auto 12px;font-size:22px;}\n.fg-item h4{font-size:15px;font-weight:700;color:#fff;}\n.fg-item p{font-size:12px;color:rgba(255,255,255,.4);}\n</style>`},

{id:'cta-banner',title:'CTA Banner',category:'cta',tags:['cta','banner','action'],desc:'Full-width call-to-action with gradient background.',featured:false,isNew:true,
preview:`<style>body{margin:0;font-family:Inter,sans-serif;background:#0b0f1a;display:flex;align-items:center;justify-content:center;height:100vh;padding:10px;}.ctab{width:100%;padding:28px 24px;background:linear-gradient(135deg,rgba(124,58,237,.15),rgba(37,99,235,.1));border:1px solid rgba(124,58,237,.2);border-radius:16px;display:flex;align-items:center;justify-content:space-between;}.ctab-text h3{font-size:18px;font-weight:800;color:#fff;margin-bottom:4px;}.ctab-text p{font-size:11px;color:rgba(255,255,255,.5);}.ctab-btn{padding:10px 22px;background:linear-gradient(135deg,#7c3aed,#2563eb);color:#fff;border:none;border-radius:8px;font-size:12px;font-weight:700;cursor:pointer;white-space:nowrap;}</style><div class="ctab"><div class="ctab-text"><h3>Ready to get started?</h3><p>Join thousands of developers building with AURA UI.</p></div><button class="ctab-btn">Start Free →</button></div>`,
code:`<div class="ctab"><div class="ctab-text"><h3>Ready to get started?</h3><p>Join thousands of developers.</p></div><button class="ctab-btn">Start Free →</button></div>\n\n<style>\n.ctab{padding:48px 40px;background:linear-gradient(135deg,rgba(124,58,237,.15),rgba(37,99,235,.1));border:1px solid rgba(124,58,237,.2);border-radius:20px;display:flex;align-items:center;justify-content:space-between;}\n.ctab-text h3{font-size:28px;font-weight:800;color:#fff;}\n.ctab-text p{font-size:15px;color:rgba(255,255,255,.5);}\n.ctab-btn{padding:14px 28px;background:linear-gradient(135deg,#7c3aed,#2563eb);color:#fff;border:none;border-radius:10px;font-size:15px;font-weight:700;}\n</style>`},

{id:'spinner-loader',title:'Spinner Loader',category:'loader',tags:['spinner','loading','animation'],desc:'Animated gradient spinner loading indicator.',featured:false,isNew:true,
preview:`<style>body{margin:0;font-family:Inter,sans-serif;background:#0b0f1a;display:flex;align-items:center;justify-content:center;height:100vh;flex-direction:column;gap:12px;}.spinner{width:40px;height:40px;border-radius:50%;border:3px solid rgba(255,255,255,.08);border-top-color:#7c3aed;animation:spin .8s linear infinite;}@keyframes spin{to{transform:rotate(360deg);}}.spin-text{font-size:12px;color:rgba(255,255,255,.4);}</style><div class="spinner"></div><span class="spin-text">Loading...</span>`,
code:`<div class="spinner"></div>\n\n<style>\n.spinner{width:48px;height:48px;border-radius:50%;border:3px solid rgba(255,255,255,.08);border-top-color:#7c3aed;animation:spin .8s linear infinite;}\n@keyframes spin{to{transform:rotate(360deg);}}\n</style>`},

{id:'theme-toggle',title:'Theme Toggle',category:'toggle',tags:['toggle','theme','switch'],desc:'Animated sun/moon theme toggle switch.',featured:false,isNew:true,
preview:`<style>body{margin:0;font-family:Inter,sans-serif;background:#0b0f1a;display:flex;align-items:center;justify-content:center;height:100vh;gap:12px;}.tt{position:relative;width:56px;height:28px;}.tt input{display:none;}.tt-track{position:absolute;inset:0;background:rgba(255,255,255,.08);border-radius:28px;border:1px solid rgba(255,255,255,.1);cursor:pointer;transition:background .3s;}.tt-track::before{content:'☀';position:absolute;left:3px;top:3px;width:20px;height:20px;background:#fff;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:10px;transition:transform .3s cubic-bezier(.34,1.56,.64,1);}.tt input:checked~.tt-track{background:linear-gradient(135deg,#7c3aed,#2563eb);border-color:transparent;}.tt input:checked~.tt-track::before{transform:translateX(28px);content:'🌙';}.tt-label{font-size:12px;color:rgba(255,255,255,.5);font-weight:600;}</style><span class="tt-label">Light</span><label class="tt"><input type="checkbox" checked><span class="tt-track"></span></label><span class="tt-label">Dark</span>`,
code:`<label class="tt"><input type="checkbox"><span class="tt-track"></span></label>\n\n<style>\n.tt{position:relative;width:56px;height:28px;}\n.tt input{display:none;}\n.tt-track{position:absolute;inset:0;background:rgba(255,255,255,.08);border-radius:28px;border:1px solid rgba(255,255,255,.1);cursor:pointer;transition:background .3s;}\n.tt-track::before{content:'☀';position:absolute;left:3px;top:3px;width:20px;height:20px;background:#fff;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:11px;transition:transform .3s;}\n.tt input:checked~.tt-track{background:linear-gradient(135deg,#7c3aed,#2563eb);}\n.tt input:checked~.tt-track::before{transform:translateX(28px);content:'🌙';}\n</style>`},

{id:'hover-tooltip',title:'Hover Tooltip',category:'tooltip',tags:['tooltip','hover','info'],desc:'CSS-only tooltip that appears on hover.',featured:false,isNew:true,
preview:`<style>body{margin:0;font-family:Inter,sans-serif;background:#0b0f1a;display:flex;align-items:center;justify-content:center;height:100vh;}.tip-wrap{position:relative;display:inline-block;}.tip-trigger{padding:10px 20px;background:rgba(255,255,255,.06);border:1px solid rgba(255,255,255,.1);border-radius:8px;color:#fff;font-size:12px;font-weight:600;cursor:default;}.tip-box{position:absolute;bottom:calc(100% + 8px);left:50%;transform:translateX(-50%) translateY(4px);padding:6px 12px;background:#1e1b4b;border:1px solid rgba(124,58,237,.3);border-radius:6px;font-size:10px;color:#c4b5fd;white-space:nowrap;opacity:0;pointer-events:none;transition:all .2s;}.tip-box::after{content:'';position:absolute;top:100%;left:50%;transform:translateX(-50%);border:5px solid transparent;border-top-color:#1e1b4b;}.tip-wrap:hover .tip-box{opacity:1;transform:translateX(-50%) translateY(0);}</style><div class="tip-wrap"><span class="tip-trigger">Hover me</span><span class="tip-box">I'm a tooltip!</span></div>`,
code:`<div class="tip-wrap"><span class="tip-trigger">Hover me</span><span class="tip-box">Tooltip text</span></div>\n\n<style>\n.tip-wrap{position:relative;display:inline-block;}\n.tip-box{position:absolute;bottom:calc(100% + 8px);left:50%;transform:translateX(-50%) translateY(4px);padding:8px 14px;background:#1e1b4b;border:1px solid rgba(124,58,237,.3);border-radius:8px;font-size:12px;color:#c4b5fd;white-space:nowrap;opacity:0;pointer-events:none;transition:all .2s;}\n.tip-box::after{content:'';position:absolute;top:100%;left:50%;transform:translateX(-50%);border:6px solid transparent;border-top-color:#1e1b4b;}\n.tip-wrap:hover .tip-box{opacity:1;transform:translateX(-50%) translateY(0);}\n</style>`},

{id:'sidebar-nav',title:'Sidebar Nav',category:'sidebar',tags:['sidebar','menu','navigation'],desc:'Dark sidebar with icons and active state.',featured:false,isNew:true,
preview:`<style>body{margin:0;font-family:Inter,sans-serif;background:#0b0f1a;display:flex;height:100vh;}.sb{width:200px;background:#0a0e1a;border-right:1px solid rgba(255,255,255,.06);padding:16px 10px;display:flex;flex-direction:column;gap:2px;}.sb-brand{font-size:14px;font-weight:800;color:#fff;padding:8px 12px;margin-bottom:12px;}.sb-item{display:flex;align-items:center;gap:10px;padding:9px 12px;border-radius:8px;font-size:12px;font-weight:500;color:rgba(255,255,255,.5);cursor:pointer;transition:all .2s;}.sb-item:hover{background:rgba(255,255,255,.04);color:rgba(255,255,255,.8);}.sb-item.active{background:rgba(124,58,237,.12);color:#a78bfa;}.sb-ic{font-size:14px;width:20px;text-align:center;}.sb-sep{height:1px;background:rgba(255,255,255,.06);margin:8px 12px;}</style><div class="sb"><div class="sb-brand">⬡ Dashboard</div><div class="sb-item active"><span class="sb-ic">◫</span>Overview</div><div class="sb-item"><span class="sb-ic">📊</span>Analytics</div><div class="sb-item"><span class="sb-ic">👥</span>Users</div><div class="sb-sep"></div><div class="sb-item"><span class="sb-ic">⚙</span>Settings</div><div class="sb-item"><span class="sb-ic">❓</span>Help</div></div>`,
code:`<div class="sb"><div class="sb-brand">⬡ Dashboard</div><div class="sb-item active"><span class="sb-ic">◫</span>Overview</div><div class="sb-item"><span class="sb-ic">📊</span>Analytics</div></div>\n\n<style>\n.sb{width:260px;background:#0a0e1a;border-right:1px solid rgba(255,255,255,.06);padding:20px 12px;display:flex;flex-direction:column;gap:2px;}\n.sb-brand{font-size:16px;font-weight:800;color:#fff;padding:10px 14px;margin-bottom:16px;}\n.sb-item{display:flex;align-items:center;gap:12px;padding:10px 14px;border-radius:10px;font-size:13px;color:rgba(255,255,255,.5);cursor:pointer;}\n.sb-item:hover{background:rgba(255,255,255,.04);color:#fff;}\n.sb-item.active{background:rgba(124,58,237,.12);color:#a78bfa;}\n</style>`},

{id:'stats-dashboard',title:'Stats Dashboard',category:'dashboard',tags:['dashboard','stats','metrics'],desc:'KPI dashboard with 4 metric cards.',featured:false,isNew:true,
preview:`<style>body{margin:0;font-family:Inter,sans-serif;background:#0b0f1a;display:flex;align-items:center;justify-content:center;height:100vh;padding:10px;}.sd{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;width:300px;}.sd-card{padding:16px;background:#0f1629;border:1px solid rgba(255,255,255,.07);border-radius:12px;}.sd-label{font-size:10px;font-weight:600;color:rgba(255,255,255,.4);text-transform:uppercase;letter-spacing:.06em;margin-bottom:6px;}.sd-val{font-size:22px;font-weight:900;color:#fff;}.sd-change{font-size:10px;font-weight:700;margin-top:4px;}.sd-up{color:#34d399;}.sd-down{color:#f87171;}</style><div class="sd"><div class="sd-card"><div class="sd-label">Revenue</div><div class="sd-val">$48.2K</div><div class="sd-change sd-up">↑ 12.5%</div></div><div class="sd-card"><div class="sd-label">Users</div><div class="sd-val">2,847</div><div class="sd-change sd-up">↑ 8.3%</div></div><div class="sd-card"><div class="sd-label">Orders</div><div class="sd-val">1,234</div><div class="sd-change sd-up">↑ 5.7%</div></div><div class="sd-card"><div class="sd-label">Bounce Rate</div><div class="sd-val">24.1%</div><div class="sd-change sd-down">↓ 2.1%</div></div></div>`,
code:`<div class="sd"><div class="sd-card"><div class="sd-label">Revenue</div><div class="sd-val">$48.2K</div><div class="sd-change sd-up">↑ 12.5%</div></div>...</div>\n\n<style>\n.sd{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;}\n.sd-card{padding:24px;background:#0f1629;border:1px solid rgba(255,255,255,.07);border-radius:16px;}\n.sd-label{font-size:12px;font-weight:600;color:rgba(255,255,255,.4);text-transform:uppercase;}\n.sd-val{font-size:32px;font-weight:900;color:#fff;}\n.sd-up{color:#34d399;font-weight:700;}\n.sd-down{color:#f87171;font-weight:700;}\n</style>`}
];

// Merge into main COMPONENTS array
if(typeof COMPONENTS!=='undefined'){COMPONENTS.push(...EXTRA_COMPONENTS);}
